config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :questions do
    resources :answers

  end

  resources :users

  root 'sessions#new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  post 'sessions', to: 'sessions#create', as: 'sessions'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
     <!-- Nav Wrap -->
  <nav class="top-bar">
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name"></li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <!-- The Section wrap -->
    <section class="top-bar-section">

      <!-- Left Nav Section -->
      <ul class="left">
        <li class="active"><%= link_to "Loopoll", questions_path %></li>
      </ul>

      <!-- Right Nav Section -->
        <ul class="right">

          <% if current_user %>
              <li><%= link_to "Logged in as #{current_user.name}, id: #{current_user.id}", '#' %></li>
              <li class="active"><%= link_to "Logout", logout_path, method: :delete %></li>
          <% else %>
              <li><%= link_to "Login", root_path %></li>
          <% end %>
        </ul>
    </section>
  </nav>


    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>